### ISSUE TITLE
NS-5: IP access lists for workspace access - false positive when public network access is disabled?

### ISSUE THREAD

**Issue by v1adev** [databricks-industry-solutions/security-analysis-tool#135]
Since IP access lists for workspace access only apply to requests over public IP addresses, this rule doesn't apply to Azure Databricks workspaces that have the `publicNetworkAccess` set to `false` and should not be reported as a check failure.

**Comment by arunpamulapati** [comment]
Thank you for reporting this and we will review and update in the next release.

**Comment by arunpamulapati** [comment]
After internally discussing this we came to the conclusion that we change the recommendation statement to: 
**Configure IP access lists or private network connectivity (NS-3) for workspaces that restrict the IP addresses that can authenticate to help protect against data exfiltration and account takeover**

These are two isolated tests, and it's hard to check these mutually also, some customers may want the hybrid, i.e., both Private connectivity and IP Address allow list. 

So, an updated message may help clarify that both are not a must, but one of them is a good place to be.
