### ISSUE TITLE
Two .tfvars files

### ISSUE THREAD

**Issue by JDBraun** [databricks-industry-solutions/security-analysis-tool#145]
There are two tfvars files in the new AWS terraform branch
- https://github.com/databricks-industry-solutions/security-analysis-tool/tree/main/terraform/aws

**Comment by arunpamulapati** [comment]
Yeah, in the next release, we will not include the terraform.tfvars

**Comment by arunpamulapati** [comment]
This fixed in the release 0.3.2 . Will be pushed soon.

**Comment by arunpamulapati** [comment]
This is now released.
