### ISSUE TITLE
[REQUIRES SINGLE_PART_NAMESPACE] spark_catalog requires a single-part namespace

### ISSUE THREAD

**Issue by selahpa** [databricks-industry-solutions/security-analysis-tool#147]
I followed the setup instructions for a UC-enabled Azure Databricks workspace, however, when I run the initializer job, I get the following error:

`[REQUIRES SINGLE_PART_NAMESPACE] spark_catalog requires a single-part namespace, but got "security_analysis". "security_analysis". SQLSTATE: 42K05`

I did select the "Use Unity Catalog" option when running the install.

I believe this means the job cluster is not or is unable to use Unity Catalog. I noticed the job cluster appeared in the Workflow UI with an access mode of "custom", and that no access mode was explicitly setup in the job cluster config in the job's yaml file.

I added `data_security_mode: "SINGLE_USER"` to the yaml file templates, and that seem to have resolved the issue. So maybe that's the fix.

Perhaps this has something to do with the way our workspace is set up.

I see there is a workspace setting "Default access mode for job compute", which was set to "Not set" after a fresh workspace deployment. I did try changing this to "single user" before rerunning the init job, but ran into the same issue. (Perhaps this has to be set before the workflow is created?)

**Comment by arunpamulapati** [comment]
Thank you. We are unable to replicate the issue in our testing in our current workspace; yes, the Access mode is single user. We are looking into this by yes it should be

**Comment by arunpamulapati** [comment]
This is now fixed in release v 0.31 by forcing the job clusters SAT creates to Single user mode where workspaces have default access mode set to None. https://docs.databricks.com/en/admin/workspace-settings/default-access-mode.html#best-practices
