### ISSUE TITLE
Checks GOV-10 and GOV-11 appear to use the same exact logic

### ISSUE THREAD

**Issue by v1adev** [databricks-industry-solutions/security-analysis-tool#149]
Is the implementation for checks GOV-10 and GOV-11 functionally the same by design or is that a bug?

**Comment by arunpamulapati** [comment]
Thank you. We will review and will update the issue.

**Comment by arunpamulapati** [comment]
Its a bug. I made a hotfix. Thanks again.
https://github.com/databricks-industry-solutions/security-analysis-tool/commit/1c185b23841fb69cc2c42ee3fa3bc759d6e407ae
