### ISSUE TITLE
hostname

### ISSUE THREAD

**Issue by thbeh** [databricks-industry-solutions/security-analysis-tool#155]
Hi, I am trying to deploy SAT in an Azure testing environment but having issues with the hostname (in every notebook) returning "https://australiaeast.azuredatabricks.net"  instead of the actual hostname "https://adb-xxxxxx.xx.azuredatabricks.net". 

Please advise. Thanks

**Comment by arunpamulapati** [comment]
Hi 
What setup instructions did you user? standard or TF? 
Are you referring to the accounts console host or the workspace URL? 
Thanks for reaching out

**Comment by thbeh** [comment]
What setup instructions did you user? standard or TF? **Standard**
Are you referring to the accounts console host or the workspace URL? **Workspace URL**

This is the snippet of the JSON (I had to removed some to avoid any sensitive content)
`{
  "rootRunId": null,
  "currentRunId": null,
  "jobGroup": "1728449926361_5924733808080313717_b5c7fea53af0413890fa8d10e304c617",
  "tags": {
    ...
    "browserHostName": "adb-3XXXXXXXXXXXX.14.azuredatabricks.net",
    "parentOpId": "Driver-560517029d9a5512",
    "jettyRpcType": "InternalDriverBackendMessages$DriverBackendRequest"
  },
  "extraContext": {
    ...
    "api_url": "https://australiaeast.azuredatabricks.net",
    "objectType": "NOTEBOOK",
    ...
    "api_token": "[REDACTED]"
  },
  "credentialKeys": [
    "adls_aad_token",
    "adls_gen2_aad_token",
    "synapse_aad_token"
  ]
}`

**Comment by arunpamulapati** [comment]
Thank you.  
Looks like custom DNS is just one possible cause.
Can you send me a few EST friendly days and times to arun@databricks.com so that we can do live debug?

**Comment by thbeh** [comment]
Hi, it's not critical at the moment, so it may not be necessary for a live debug. I did a workaround by using browserHostName instead.

**Comment by arunpamulapati** [comment]
Thank you.
