### ISSUE TITLE
Error: Missing 'security_best_practices' Table.

### ISSUE THREAD

**Issue by arbaaz750** [databricks-industry-solutions/security-analysis-tool#30]
Recently we started setting up SAT for our organization, but facing error in running the setup.
**Current setup is**: 2 workspaces enabled for Analysis in Azure.
**Authentication Method**: Client Secret.
**Method used to run**: Tried both Simple and Power flexible user.
**Error**: Problem faced while running 'security_analysis_driver' notebook it is giving error as 'security_best_practices' Table not found.
****
**Screenshots**: Attaching Screenshots for the reference.
<img width="669" alt="image" src="https://user-images.githubusercontent.com/121478814/218074489-e493ccb0-d8c7-4841-8938-c71a9b5c1bed.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/121478814/218075085-bfd998a4-0167-4762-b77e-be7ec2f6a55b.png">

How to create 'security_best_practices' Table, to solve the above error? or is there any other dependency notebook which creates the table?
<img width="397" alt="image" src="https://user-images.githubusercontent.com/121478814/218075334-7f383a69-8a68-4aca-bb12-5b56b987aca7.png">

**Comment by arunpamulapati** [comment]
Hi arbaaz750,

Thank you for trying to set up SAT. Sorry to know that you are running into an issue. I am more than happy to support you to get this setup completed. 
It is likely that there is an edge case that the code is running into. Please go to <SAT_Project_Repo>configs/security_best_practices_user.csv and delete this file and rerun the driver, It will recreate the _user file from configs/security_best_practices.csv and the corresponding table if it does not see _user.csv file. 

If the issue still persists please connect with me via email: arun.pamulapati@databricks.com and I will work with your calendar to find a day/time to resolve this over a live meeting.

**Comment by arunpamulapati** [comment]
Arbaaz Shaikh, 
Just checking to see if you made progress. Nonetheless, happy to jump on a call to go over checks, feedback, or anything else we can help you with. 
Thanks
Arun

**Comment by arbaaz750** [comment]
Thanks @arunpamulapati, I tried out the the solution you gave and it worked smoothly. SAT Dashboards are generated, we'll analyse it and revert back to you if we find any issue or have any doubts.

**Comment by arunpamulapati** [comment]
That is great. I would still be interested in learning from the value you got from SAT, please let me know if you are interested in co-author a blog with me on Databricks.com/blog and/or speaking to our team to give feedback etc. 
We are constantly updating SAT and look forward to your feedback. My email is: arun.pamulapati@databricks.com in case you need anything in the future.
