### ISSUE TITLE
Where to install the databricks CLI?

### ISSUE THREAD

**Issue by hillaryzhang** [databricks-industry-solutions/security-analysis-tool#31]
Hello, I'm reading the page "https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/docs/setup.md".

I'm wondering where to install the Databricks CLI. Should I install it on the Single User Cluster? On any of the nodes? Or on all nodes of the cluster?  How do I access the shell on the machine? Through SSH? Or through Web Terminal? 

Please make it clear in the "setup.md" or this doc becomes another hindrance for developers to use Databricks.

**Comment by arunpamulapati** [comment]
Hi @hillaryzhang ,
Thank you for reaching out with your question. 
You will install the Databricks CLI on your work machine such as your laptop or virtual desktop that can reach your Databricks workspaces. 
I updated the instructions. Please get in touch with your Databricks account team or me if you run into any issues. 

Thank you
Arun
