### ISSUE TITLE
Unable to see data in databricks dashboard

### ISSUE THREAD

**Issue by sadhana-kharol** [databricks-industry-solutions/security-analysis-tool#44]
**Steps Followed for set up -:** 

1- Cloned the git repo in our  azure databricks environment (https://github.com/databricks-industry-solutions/security-analysis-tool).
2- Created the secret-scope and configured the secrets as mentioned in the document and followed all the steps for running the SAT tool as per the setup.md file in the docs folder of the repo.
3- Ran the Security_analysis_initializer and security_analysis_driver notebooks.

**Problem Statement :** 

1- Even though the Security_analysis_initializer file runs completely without any error(internally running all the files in the setup folder),it does not create any dashboard in the SQL warehouse.

2- In hivemetastore database security analysis get created with all the tables but except "hive_metastore.security_analysis.account_workspaces” ,no table gets populated with data.

3- In the account_workspaces table the column connection_test shows false even if the connection_test successful gets reflected while running the Security_analysis_initializer notebook.

While calling the test_connection function in the test_connections notebook in the setup folder,we observed that while establishing a connection for the account "True" is passed as the second parameter and the connection was successfully established.
But while calling the test_connection function while connecting to the workspace , the value for the second parameter was passed as False.If we run the code w/o making any changes, connection is not established.
![image](https://user-images.githubusercontent.com/128048268/225613256-13b91e35-d54b-42af-bc01-157bc128a37c.png)

So we tried running it by passing "True" as the second parameter and the connection got established.

![image](https://user-images.githubusercontent.com/128048268/225611875-716ea1e9-2763-48f2-ba9f-5fce4f24b576.png)

**Steps taken care of -:** 

1- We made sure the cluster configuration,SQL warehouse config matches the setup doc .
2- Both the SAT cluster and the SQL warehouse are in running state while we run the  Security_analysis_initializer and  notebook and the security_analysis_driver notebook.
3- Have all the admin access for Azure active directory as well as the workspace and management console.
4- All the secrets are configured correctly.
5- The dashboard template gets created and the dropdown for the workspaces also appear that we can choose to analyse.But  if we select any workspace and click on apply changes there is no information available in the form of charts as the tables don't get populated.
![3](https://user-images.githubusercontent.com/128048268/225613629-8245b341-a7b5-4d14-86ca-ad36e7d46dd3.png)

cc: @MohitRathore97

**Comment by arunpamulapati** [comment]
Hi @sadhana-kharol and @MohitRathore97 
Thank you for reaching.
I think it is best to check the configurations over a call. I am happy to work with you. Please reach me via arun.pamulapati@databricks.com with a few days, times slots, and your time zone availability. I am in US EST. 

Thank you.
Arun

**Comment by NathNachtje** [comment]
Can you please document or add the output of the meeting? What was the issue. I had the same, but was thinking it was because there is not much in my workspace I am running it on

**Comment by sadhana-kharol** [comment]
Hi  @arunpamulapati 
 
Thanks for the quick reply .The issue got resolved for us. It was indeed a configuration issue. As per your mail, we thoroughly checked again all the configs that were set, and it's working fine for us now.

@NathNachtje We didnt had any meeting as such. Maybe you can post your exact issue here and we can look into it,

**Comment by arunpamulapati** [comment]
Thank you. Please reach me at arun.plamulapati@databricks.com or sat@databricks.com if you need further assistance. I am closing this issue.
