### ISSUE TITLE
SAT - Security Analysis Tool implementation error

### ISSUE THREAD

**Issue by ArnoldSouza** [databricks-industry-solutions/security-analysis-tool#46]
I want to implement SAT in my workspace account. I was able to execute the terraform that enable the necessary infra to work on that. When I try to execute the workflow "SAT Initializer Notebook (one-time)" it fails with the error:

AnalysisException: [UNRESOLVED_COLUMN.WITHOUT_SUGGESTION] A column or function parameter with the name `workspace_status` cannot be resolved.

![1](https://user-images.githubusercontent.com/35499672/226079356-fd36c7e6-b882-4477-8b09-bdc2abcb06fb.JPG)

Upon further investigation I figured out the problem is located in the notebook '../Utils/accounts_bootstrap' is failing when it tries to fetch API information.

![2](https://user-images.githubusercontent.com/35499672/226079360-eb3a81f8-18d7-4eae-8a11-3b8026576956.JPG)

So the global views that are the base of the notebooks are being created as an empty data frame.

Can someone help me figure out a solution to that?

**Comment by arunpamulapati** [comment]
This is resolved by adding the service principle with "Reader" role into the subscription level via Access control (IAM) using Role assignments under your [subscription, Access control (IAM) section](https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal#step-2-open-the-add-role-assignment-page).
Thank you. Now the instructions clarify in both Terraform and the setup instructions.
