### ISSUE TITLE
Azure_SAT Deployment Checklist not in line with documentation

### ISSUE THREAD

**Issue by NathNachtje** [databricks-industry-solutions/security-analysis-tool#47]
databricks --profile e2-sat secrets put --scope sat_scope --key account-console-id
databricks --profile e2-sat secrets put --scope sat_scope --key sql-warehouse-id
databricks --profile e2-sat secrets put --scope sat_scope --key user-email-for-alerts
databricks --profile e2-sat secrets put --scope sat_scope --key subscription-id
databricks --profile e2-sat secrets put --scope sat_scope --key tenant-id
databricks --profile e2-sat secrets put --scope sat_scope --key client-id

Are not available/mentioned in the checklist, but are part of the setup.md

**Comment by arunpamulapati** [comment]
Thank you @NathNachtje we will update the sheets with the changes we did for the Terraform release. In the meanwhile please let me know if you run into any issues. Feel free to reach me at arun.pamulapati@databricks.com . Thank you.

**Comment by arunpamulapati** [comment]
Updated checklists. Video version of the setup coming soon. 
Thanks for your support. 
Arun
arun@databricks.com
