### ISSUE TITLE
accounts_bootstrap error running SAT security_analysis_driver notebook

### ISSUE THREAD

**Issue by sbarrick** [databricks-industry-solutions/security-analysis-tool#57]
I was able to complete the prerequisite steps and successfully run the security_analysis_initializer notebook, but the account_bootstrap failed during the driver notebook execution.

![Screenshot 2023-05-01 at 10 19 23 AM](https://user-images.githubusercontent.com/46822875/235701563-55f2131c-1d47-4286-a11e-c801f0b655e0.png)

After the initial manual attempted, I rewatched the tutorial video and recreated the secrets scope using terraform, but ran into the same error.  It's certainly possible that there is human error in the prerequisite collection or scope creation, but I'm not sure how to start troubleshooting further from this state.

**Comment by arunpamulapati** [comment]
Hi Shawn Barrick (@sbarrick ), please contact me at arun@databricks.com with a few days and timeslots best for you to review your setup over a call. I am in the US EST time zone.

**Comment by arunpamulapati** [comment]
This was due to the use of an incorrect admin account.
