### ISSUE TITLE
security_analysis_initializer notebook error

### ISSUE THREAD

**Issue by mwarqee** [databricks-industry-solutions/security-analysis-tool#60]
After setting up the SAT manually, while running the , **security_analysis_initializer** I got the following error:

```
Message: 'Error Encountered in Step#5'
Arguments: ('The current workspace is not found in configured list of workspaces for analysis.',)
```

However I have setup the workspace id as required in the instructions manual, via databricks cli. Does anyone have any suggestion for debug/additional logs?

**Comment by arunpamulapati** [comment]
Hi @mwarqee please send me a few days and times that are best for you to get on a call. You can reach me at arun@databricks.com. I am in the EST time zone.  Also, let me know if this is for Databricks on AWS or Azure.

**Comment by mwarqee** [comment]
Forgot to add SP to the Databricks workspace during manual setup. Once that was done, notebook completed succesfully.
