### ISSUE TITLE
403 error when using SAT on GCP databricks

### ISSUE THREAD

**Issue by zhichaoleo** [databricks-industry-solutions/security-analysis-tool#62]
Hi Team,
We are using this tool on GCP databricks. Following the document: https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/docs/setup.md, but we still get the 403 error when we run the notebook: security_analysis_initializer.

<img width="1485" alt="image" src="https://github.com/databricks-industry-solutions/security-analysis-tool/assets/13878193/84a9ae61-8614-4387-9a13-a928ec1a6554">

This notebook create a new job to run notebook configure_sa_auth_tokens, here we got the error:
<img width="965" alt="image" src="https://github.com/databricks-industry-solutions/security-analysis-tool/assets/13878193/edc516b3-c7aa-4b00-ac6a-17d918412746">

Service accounts SA1 & SA2 has been added to this workspace by our account admin, these two service accounts has been added to this workspace's admin.  Also, account-console-id is my account_id, PAT was generated using my account.  
<img width="765" alt="image" src="https://github.com/databricks-industry-solutions/security-analysis-tool/assets/13878193/2f1ad530-2692-49a7-8cb7-e09844c853d5">
<img width="604" alt="image" src="https://github.com/databricks-industry-solutions/security-analysis-tool/assets/13878193/c1e47a82-3f16-4fd9-bf8b-1dee965857b3">

Don't know why we got this 403 error.

Could you help me with this error?

Thanks,
Alex

**Comment by arunpamulapati** [comment]
Hi Alex, Please reach me at arun@databricks.com with a few days and time slots that work best for you. I am in EST time zone. We can go over your setup and review the configuration.

Thank you
Arun

**Comment by zhichaoleo** [comment]
Sure, Arun. Will have a contact via email. Thanks!

Regards,
Alex

**Comment by zhichaoleo** [comment]
Thanks for your kindly help. The problem is service account don't have the permission.
