### ISSUE TITLE
Workspace is not appearing on the dashboard

### ISSUE THREAD

**Issue by jka171** [databricks-industry-solutions/security-analysis-tool#69]
Hi, I followed all the steps in the video and on Git and still I can't see my other workspaces on the dashboard. if I do a select statement on the database I see all the information.

Please can you assist, thanks

**Comment by jka171** [comment]
I did add the service principle to the other workspace, but still having the same issue

**Comment by arunpamulapati** [comment]
This is likely the cache issue in the dashboard, not an issue with SAT. Please go to the query behind the dashboard and run it by hand. 
Goto SQL view of your Databricks workspace -> Goto Queries -> Filer by Tags (SAT) -> find the query -> "workspace_ids" and run it. Please confirm if you see both of the workspaces. 
Then go back to the dashboard and refresh it. Now you should see the pulldown with both workspaces.
Sorry for the incontinence. Once you confirm, I will add this to the FAQs.

**Comment by jka171** [comment]
@arunpamulapati thank you, what I did is reinstalled everything and just before I open the dashboard I checked the query and it still showed an old refresh date on it, so what I did is to refresh the query as per your instructions and then it worked.

So what I did for that specific query I set up a refresh for once a day, so I'll monitor it for this week and see

**Comment by arunpamulapati** [comment]
Thank you for the update.
