### ISSUE TITLE
Issue while running 'security_analysis_initializer' notebook

### ISSUE THREAD

**Issue by pranavlavanya** [databricks-industry-solutions/security-analysis-tool#71]
I have tried couple of times to setup the pre-requisites as per the setup documentation, however I'm facing the below error while running 'security_analysis_initializer' notebook, specifically when it calls the notebook '5. import_dashboard_template'. the error is shown below.

![image](https://github.com/databricks-industry-solutions/security-analysis-tool/assets/71499437/8a232e97-7787-4162-9740-88f94f62e8d2)

Can you help me troubleshoot?

**Comment by pranavlavanya** [comment]
@arunpamulapati sorry for the delayed response, im running it on Azure.

**Comment by arunpamulapati** [comment]
I ran a test on Azure with SAT and it was able to run smoothly as expected. It looks like either the PAT token that is used to import the dashboard likely missing or not set up right. You can reach me at arun@databricks.com with a few days/time slots so that we can have a short call to unblock you.

**Comment by pranavlavanya** [comment]
Sure @arunpamulapati thank you!
