### ISSUE TITLE
Manual Setup Guide follows legacy Databricks CLI logic

### ISSUE THREAD

**Issue by bbonekamp** [databricks-industry-solutions/security-analysis-tool#74]
De documentation uses https://docs.databricks.com/en/archive/dev-tools/cli/index.html# instead of https://docs.databricks.com/en/dev-tools/cli/databricks-cli.html, meaning that deprecated flags as --scope are used. 

The new CLI requires commands as put-secret instead of --key etc.

**Comment by arunpamulapati** [comment]
Thank you @bbonekamp we will review these instructions and update them. If you wish to, we are happy to take the pull request and verify and merge incase you already have the changes/fixes.

**Comment by arunpamulapati** [comment]
This is fixed now. Thank you.
