### ISSUE TITLE
how to analyze workspaces without PAT ?

### ISSUE THREAD

**Issue by gkoenig** [databricks-industry-solutions/security-analysis-tool#77]
Hello,
I am running several workspaces in Azure and I created a PAT token for each workspace to enable analyzing them.
I also have workspaces which I want to analyze, but there the **generation of PAT tokens is disabled** via the workspace settings.
Any chance to add those workspaces to the list of being analyzed ?

Many thanks in advance

**Comment by arunpamulapati** [comment]
If you are still having issues please send me an email with your availability for a live call. I am at arun@databricks.com and I am in EST timezone.

**Comment by gkoenig** [comment]
Hello Arun,

many thanks for offering your support via a live call, and I would be more
than happy to get in direct contact with you.
The current issue got solved by your recommendation, but maybe we get
another chance if I am facing follow-up issues while evaluating SAT for
current customer project.

Best regards (from Switzerland),

Gerd
