### ISSUE TITLE
Dashboard shows only one workspace in drop-down

### ISSUE THREAD

**Issue by gkoenig** [databricks-industry-solutions/security-analysis-tool#78]
Hello,
I've setup SAT on one of our Azure subscriptions, containing several workspaces to be analyzed, but unfortunately the dashboard only shows one workspace in the drop-down box for selecting "workspace", which is the workspace where sat is hosted (the "current workspace" in the wording of the notebook).
I went through the manual setup successfully (at least both notebooks "security_analysis_initializer" and "security_analysis_driver" finished without error), but didn't find any hint why the dashboard doesn't offer me the remaining workspaces to choose.

Some more details:

- 4 workspaces have been configured to be analyzed
- all 4 passed the connection tests
- the table _hive_metastore.security_analysis.account_workspaces_ contains all 4 workspaces and each entry has flag "**analysis_enabled**" set to **true**
- in notebook "6. configure alert templates" there is statement _spark.sql('select * from `global_temp`.`all_workspaces`')_ , which also returns all 4 workspaces with flags "analysis_enabled" and "connection_test" both set to "true"

Any hint why the dashboard only shows one out of the 4 workspaces in the drop-down box is highly appreciated, where to continue troubleshooting, which tables/statements to check , etc...

Many thanks in advance

**Comment by arunpamulapati** [comment]
Its likely a cache issue. Please review this FAQ # 3 and let me know if that fixes the problem. 
https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/docs/setup.md#faqs

It is likely that the Dashboard cached the workspaces in the pulldown. You can go to SQL view of your workspace -> Queries -> find workspace_ids query and run it, that should refresh and have the new workspaces in the pull-down.

**Comment by gkoenig** [comment]
Hello @arunpamulapati ,
many thanks for your quick response.
Your suggestion of "rerunning the query" solved the issue :+1:
