### ISSUE TITLE
Security Configuration Comparison is not displaying data

### ISSUE THREAD

**Issue by jka171** [databricks-industry-solutions/security-analysis-tool#79]
Hi,

Im trying to use Security Configuration Comparison screen but no data is returned even after I made changes to my workspace

**Comment by arunpamulapati** [comment]
Hi JKA171, I can help debug the issue. Can you please send me a few days and times for early next week that are best for you for an hour of live call? I am in the EST timezone in the USA.

**Comment by jka171** [comment]
Hi Arun,

Thanks, send you an email.

**Comment by arunpamulapati** [comment]
This was due to not having any runsduring the date selected. Improvements to follow to make this scenario easy.
