### ISSUE TITLE
Incorrect information displayed on my dashboard for Workspace Name, Pricing tier and Region

### ISSUE THREAD

**Issue by jka171** [databricks-industry-solutions/security-analysis-tool#80]
Hi,

I added a new workspace in the workspace config csv and rerun the security_analysis_initializer and security_analysis_driver
again but the info comes up with my workspaceID instead of the Workspace Name, Pricing tier and Region

**Comment by arunpamulapati** [comment]
Hi JKA171, I can help debug the issue. Can you please send me a few days and times for early next week that are best for you for an hour of live call? I am in the EST timezone in the USA.

**Comment by jka171** [comment]
Hi Arun,

Thanks, send you an email.

**Comment by arunpamulapati** [comment]
This was due to using SAT cross subscription. One SAT setup per Azure subscription is needed.
