### ISSUE TITLE
Azure Databricks SAT Tool 403 error.

### ISSUE THREAD

**Issue by pkolluri-rev** [databricks-industry-solutions/security-analysis-tool#82]
Trying to install SAT Tool on azure databricks and in the cell with the following code

import requests
DOMAIN = ws.deployment_url
TOKEN =  dbutils.secrets.get(json_['workspace_pat_scope'], ws.ws_token)
print(json_['workspace_pat_scope'])
loggr.info(f"Looking for data_source_id for : {json_['sql_warehouse_id']}!")
response = requests.get(
          'https://%s/api/2.0/preview/sql/data_sources' % (DOMAIN),
          headers={'Authorization': 'Bearer %s' % TOKEN},
          json=None,
          timeout=60
        )

print(response)
resources = json.loads(response.text)

found = False
for resource in resources:
    if resource['endpoint_id'] == json_['sql_warehouse_id']:
        data_source_id = resource['id']
        loggr.info(f"Found data_source_id for : {json_['sql_warehouse_id']}!")
        found = True
        break
           
if (found == False:disappointed_face:
    dbutils.notebook.exit("The configured SQL Warehouse Endpoint is not found.")

And when trying to run this code 
import requests
DOMAIN = ws.deployment_url
TOKEN =  dbutils.secrets.get(json_['workspace_pat_scope'], ws.ws_token)
print(json_['workspace_pat_scope'])
loggr.info(f"Looking for data_source_id for : {json_['sql_warehouse_id']}!")
response = requests.get(
          'https://%s/api/2.0/preview/sql/data_sources' % (DOMAIN),
          headers={'Authorization': 'Bearer %s' % TOKEN},
          json=None,
          timeout=60
        )

print(response)
Getting a 403 error. The token and api pair work ok when we tried to get a response in CLI not sure why its not working in databricks.

**Comment by arunpamulapati** [comment]
Please send me your availability of days and times for this and early next week for a live debugging call after watching the Azure setup video: https://www.youtube.com/watch?v=xAav6GslSd8 . I am in EST.

**Comment by arunpamulapati** [comment]
Please send me an invite for Thursday 9:30 AM EST to arun@databricks.com or send me your email I will send you an invite.

**Comment by pkolluri-rev** [comment]
Here is my email 2022111@hawkb.us. Thank you.

**Comment by pkolluri-rev** [comment]
Hi Arun, sent you a teams invite for 9/20/2023 9:30 AM EST. Thank you.

**Comment by arunpamulapati** [comment]
This is resolved by adding the public IP of the data plane NAT to the allow list so that the rest APIs can be reached from databricks cluster to workspace rest API endpoint
