### ISSUE TITLE
SAT_dashboard - Workspace: Could not load options

### ISSUE THREAD

**Issue by davidsoliven** [databricks-industry-solutions/security-analysis-tool#83]
security-analysis-tool/notebooks/security_analysis_initializer
security-analysis-tool/notebooks/security_analysis_driver

Both notebooks ran completed using a Service Principal. However, when I load the SAT_dashboard no data is displayed. 
Workspace dropdown does not load the single workspace in our account. 

I went to Queries, filtered by Tag 'SAT' and tried running `workspace_ids` query manually. 
The table or view security_analysis.account_workspaces cannot be found.

Checked workspace_configs.csv and confirmed that analysis_enabled is True. 
Confirmed in Workspace Configuration that Analysis Enabled is True.

**Comment by arunpamulapati** [comment]
Hi @davidsoliven can you please send me a few days, times and timezone that is best for a 60 min call so that I can help debug?  Which cloud are you on?  My email is arun@databricks.com. 
My apologies for the delay in responding.

**Comment by arunpamulapati** [comment]
This is resolved by checking the cluster permissions.
