### ISSUE TITLE
Getting error when retrieving databricks_current_user and databricks_spark_version

### ISSUE THREAD

**Issue by n2dTechno** [databricks-industry-solutions/security-analysis-tool#85]
I have workspace access not to the account level. Getting below error

databricks_current_user
**Error** : Cannot read current user: default auth cannot configure default credentials

databricks_spark_version
**ERROR**  = Cannot read spark version: default auth:cannot configure default credentials

Please let me know minimum permission required to run SAT tool and solve above problem

**Comment by arunpamulapati** [comment]
Hi please send an email to arun@databricks.com with a few days and EST friendly times for next week to debug this live

**Comment by arunpamulapati** [comment]
This is resolved now. This was due to API drift. we added an exception handling condition. We will review the APIs as part of the next version.

**Comment by arunpamulapati** [comment]
Sorry, please follow the setup guide. https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/docs/setup.md

**Comment by n2dTechno** [comment]
Thank you
