### ISSUE TITLE
databricks cli sat setup commands are outdated and not working

### ISSUE THREAD

**Issue by dmchakram** [databricks-industry-solutions/security-analysis-tool#86]
HI 

I am trying to deploy SAT for my workspace  and many of commands in the below link are not working 
https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/docs/setup.md 

please check and update them

**Comment by dmchakram** [comment]
@arunpamulapati   please check on this issue

**Comment by arunpamulapati** [comment]
We are in the process of updating. Stay tuned. But in the meanwhile, you can find the equivalent commands from our docs.

**Comment by arunpamulapati** [comment]
This is fixed now.
