### ISSUE TITLE
Cannot create secret scope error default auth:

### ISSUE THREAD

**Issue by n2dTechno** [databricks-industry-solutions/security-analysis-tool#88]
We are running AWS terraform code to deploy the SAT tool to our environment
But when we run the terraform apply below error showing. We are running with account admin credentials

Canon create secret scope error default auth:
resource "databricks_secret_scope" "app"{

same way we are getting error for repo and cluster too.

If I comment the SAT code, other databricks module works good

Please help us

**Comment by arunpamulapati** [comment]
Are you using a service principle? Please make sure the service principal has access to the workspace where those resources are trying to be created.

**Comment by n2dTechno** [comment]
I am creating with account admin account, Our terraform code creates the new workspace and after setting up SAT tool

**Comment by arunpamulapati** [comment]
Please send us a few days and times to arun@databricks.com for Monda and Tuesday that are EST friendly we will debug this over a 30 min call..
