### ISSUE TITLE
new workspace is not adding and showing in existing sat 

### ISSUE THREAD

**Issue by dmchakram** [databricks-industry-solutions/security-analysis-tool#89]
HI @arunpamulapati 

I followed all the instructions and enabled the SAT tool . It is working fine for one workspace . When i tried to add another workspace by adding the service principal as admin to the workspace from accounts portal .  Then ran the sat intializer and sat driver .

But the new worksapce is not getting picked up and not even reflected in config file .

Please help me on this

**Comment by arunpamulapati** [comment]
It's likely a cache issue. Got to your SQL > Queries > workspace_ids query and run it manually and go to the dashboard to see if it has no the new workspace in the pull-down.

**Comment by arunpamulapati** [comment]
Please send us a few days and times to [arun@databricks.com](mailto:arun@databricks.com) for Monday and Tuesday that are EST friendly we will debug this over a 30 min call..

**Comment by dmchakram** [comment]
Thanks @arunpamulapati for monday and tuesday i am available from 9 AM EST/EDT to 12:30 PM EST/EDT 

ist - 7:30 PM to 10:30 PM IST

please provide your available timings i will send you an invite at the earliest .

**Comment by arunpamulapati** [comment]
Thnak you. please send me an invite for 10 AM EST for Tuesday the 19th. You can send it to arun@databricks.com

**Comment by arunpamulapati** [comment]
After going over the call, we discovered that the new workspace is in a different subscription. SAT is built to monitor multiple workspaces in a given subscription. If there are multiple subscriptions, a separate SAT instance is needed. We will add an FAQ to reflect this.
