### ISSUE TITLE
How to deploy the dbl-sat-sdk from jfrog private repository

### ISSUE THREAD

**Issue by n2dTechno** [databricks-industry-solutions/security-analysis-tool#92]
We would like to pull the dbl-sat-sdk library  from JFrog repository because Databricks does not have internet access connected to VPC

library {
    pypi {
      package = "dbl-sat-sdk"
    }
  }

**Comment by ramdaskmdb** [comment]
can you install dbl-sat-sdk to your local artifactory and in notebooks/install_sat_sdk point to your artifactory with pip install.

**Comment by n2dTechno** [comment]
We are planning to install and configure through Terraform. If we can reference package url in terraform code that would be better. Tried to avoid manual deployment

**Comment by arunpamulapati** [comment]
We will consider it for future improvement. But consider using the workaround until then.
