### ISSUE TITLE
Check ID 8: Fails with Unresolved Column Variable

### ISSUE THREAD

**Issue by rajj281** [databricks-industry-solutions/security-analysis-tool#95]
When we run the SAT tool certain check IDs are failing for us. Our Environment is on Azure

[UNRESOLVED_COLUMN.WITHOUT_SUGGESTION] A column, variable, or function parameter with name `log_type` cannot be resolved.  SQLSTATE: 42703; line 4 pos 14;
'Project ['config_name, 'config_id AS from#37056]
+- 'Filter (('log_type = AUDIT_LOGS) AND ('status = ENABLED))
   +- SubqueryAlias global_temp.acctlogdelivery
      +- View (`global_temp`.`acctlogdelivery`, [])
         +- LogicalRDD false

We are facing similar issues with 

Check ID=22
Check ID=64
Check ID=26
CheckID=6
CheckID=54
CheckID=55
CheckID=56

**Comment by arunpamulapati** [comment]
There has been a drift in our REST API - we fixed some and working on making SAT in-line with out RESP APIs. 
Please pull the latest and see if these issues exist. 
We will test these and will update the checks.

**Comment by rajj281** [comment]
Hi Arun

After pulling the latest main branch from github the following checked fail with "unresolved_column.with_suggestions"

check_id='6
check_id='8'
check_id='22'
check_id='26'
check_id='33'
check_id='54'
check_id='55'
check_id='56'
check_id='64'

**Comment by arunpamulapati** [comment]
We fixed these issues. We are continuously improving and will make more releases this month to update SAT setup , new checks as wells as bug fixes.
